input.onButtonPressed(Button.A, function () {
    robotbit.GeekServo2KG(robotbit.Servos.S8, 0)
    basic.pause(2000)
    robotbit.GeekServo2KG(robotbit.Servos.S7, 50)
    basic.pause(2000)
    robotbit.GeekServo2KG(robotbit.Servos.S8, 180)
    robotbit.GeekServo2KG(robotbit.Servos.S1, 180)
    basic.pause(2000)
    robotbit.GeekServo2KG(robotbit.Servos.S7, 180)
    robotbit.GeekServo2KG(robotbit.Servos.S2, 260)
    basic.pause(2000)
    robotbit.GeekServo2KG(robotbit.Servos.S3, 0)
    robotbit.GeekServo2KG(robotbit.Servos.S1, 0)
    basic.pause(2000)
    robotbit.GeekServo2KG(robotbit.Servos.S4, 70)
    robotbit.GeekServo2KG(robotbit.Servos.S2, 140)
    basic.pause(2000)
    robotbit.GeekServo2KG(robotbit.Servos.S6, 280)
    robotbit.GeekServo2KG(robotbit.Servos.S3, 180)
    basic.pause(2000)
    robotbit.GeekServo2KG(robotbit.Servos.S5, 90)
    robotbit.GeekServo2KG(robotbit.Servos.S4, 0)
    basic.pause(2000)
    robotbit.GeekServo2KG(robotbit.Servos.S6, 0)
    basic.pause(2000)
    robotbit.GeekServo2KG(robotbit.Servos.S5, 180)
})
input.onButtonPressed(Button.AB, function () {
    robotbit.GeekServo2KG(robotbit.Servos.S1, 0)
    robotbit.GeekServo2KG(robotbit.Servos.S2, 140)
    robotbit.GeekServo2KG(robotbit.Servos.S3, 180)
    robotbit.GeekServo2KG(robotbit.Servos.S4, 0)
    robotbit.GeekServo2KG(robotbit.Servos.S5, 180)
    robotbit.GeekServo2KG(robotbit.Servos.S6, 0)
    robotbit.GeekServo2KG(robotbit.Servos.S7, 180)
    robotbit.GeekServo2KG(robotbit.Servos.S8, 180)
})
basic.showString("KITTEN-SPIDER BOT ")
